name: Generate Snake

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 0:00 运行
  workflow_dispatch:      # 支持手动运行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            public/github-snake.svg
            public/github-snake-dark.svg?palette=github-dark
            public/github-snake-light.svg?palette=github-light
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add public/github-snake*.svg
          git commit -m "🐍 update contribution graph"
          git push
